#include "storage.h"
#include "scsiglue.h"
#include "transport.h"
#include "protocol.h"

/* The entries in this table, except for final ones here
 * (USB_MASS_STORAGE_CLASS and the empty entry), correspond,
 * line for line with the entries of us_unsuaul_dev_list[].
 */

#define UNUSUAL_DEV(id_vendor, id_product, bcdDeviceMin, bcdDeviceMax, \
		    vendorName, productName,useProtocol, useTransport, flags) \
{ USB_DEVICE_VER(id_vendor, id_product, bcdDeviceMin,bcdDeviceMax) }

static struct usb_device_id storage_usb_ids [] = {

#	include "unusual_devs.h"
#undef UNUSUAL_DEV
	/* Control/Bulk transport for all SubClass values */
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_RBC, US_PR_CB) },
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_8020, US_PR_CB) },
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_QIC, US_PR_CB) },
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_UFI, US_PR_CB) },
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_8070, US_PR_CB) },
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_SCSI, US_PR_CB) },

	/* Control/Bulk/Interrupt transport for all SubClass values */
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_RBC, US_PR_CBI) },
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_8020, US_PR_CBI) },
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_QIC, US_PR_CBI) },
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_UFI, US_PR_CBI) },
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_8070, US_PR_CBI) },
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_SCSI, US_PR_CBI) },

	/* Bulk-only transport for all SubClass values */
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_RBC, US_PR_BULK) },
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_8020, US_PR_BULK) },
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_QIC, US_PR_BULK) },
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_UFI, US_PR_BULK) },
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_8070, US_PR_BULK) },
	{ USB_INTERFACE_INFO(USB_CLASS_MASS_STORAGE, US_SC_SCSI, US_PR_BULK) },

	/* Terminating entry */
	{ }
};

/* This is the list of devices we recognize, along with their flag data */

/* The vendor name should be kept at eight characters or less, and
 * the product name should be kept at 16 characters or less. If a device
 * has the US_FL_FIX_INQUIRY flag, then the vendor and product names
 * normally generated by a device thorugh the INQUIRY response will be
 * taken from this list, and this is the reason for the above size
 * restriction. However, if the flag is not present, then you
 * are free to use as many characters as you like.
 */

#undef UNUSUAL_DEV
#define UNUSUAL_DEV(idVendor, idProduct, bcdDeviceMin, bcdDeviceMax, \
		    vendor_name, product_name, use_protocol, use_transport, Flags) \
{ \
	.vendorName = vendor_name,	\
	.productName = product_name,	\
	.useProtocol = use_protocol,	\
	.useTransport = use_transport,	\
	.flags = Flags, \
}

static struct us_unusual_dev us_unusual_dev_list[] = {
#	include "unusual_devs.h"
#	undef UNUSUAL_DEV
	/* Control/Bulk transport for all SubClass values */
	{ .useProtocol = US_SC_RBC,
	  .useTransport = US_PR_CB},
	{ .useProtocol = US_SC_8020,
	  .useTransport = US_PR_CB},
	{ .useProtocol = US_SC_QIC,
	  .useTransport = US_PR_CB},
	{ .useProtocol = US_SC_UFI,
	  .useTransport = US_PR_CB},
	{ .useProtocol = US_SC_8070,
	  .useTransport = US_PR_CB},
	{ .useProtocol = US_SC_SCSI,
	  .useTransport = US_PR_CB},

	/* Control/Bulk/Interrupt transport for all SubClass values */
	{ .useProtocol = US_SC_RBC,
	  .useTransport = US_PR_CBI},
	{ .useProtocol = US_SC_8020,
	  .useTransport = US_PR_CBI},
	{ .useProtocol = US_SC_QIC,
	  .useTransport = US_PR_CBI},
	{ .useProtocol = US_SC_UFI,
	  .useTransport = US_PR_CBI},
	{ .useProtocol = US_SC_8070,
	  .useTransport = US_PR_CBI},
	{ .useProtocol = US_SC_SCSI,
	  .useTransport = US_PR_CBI},

	/* Bulk-only transport for all SubClass values */
	{ .useProtocol = US_SC_RBC,
	  .useTransport = US_PR_BULK},
	{ .useProtocol = US_SC_8020,
	  .useTransport = US_PR_BULK},
	{ .useProtocol = US_SC_QIC,
	  .useTransport = US_PR_BULK},
	{ .useProtocol = US_SC_UFI,
	  .useTransport = US_PR_BULK},
	{ .useProtocol = US_SC_8070,
	  .useTransport = US_PR_BULK},
	{ .useProtocol = US_SC_SCSI,
	  .useTransport = US_PR_BULK},

	/* Terminating entry */
	{ NULL }
};

/*
 * fill_inquiry_response takes an unsigned char array (which must
 * be at least 36 characters) and populates the vendor name,
 * product name, and revision fields. Then the array is copied
 * into the SCSI command's response buffer (oddly enough
 * called request_buffer). data_len contains the length of the
 * data array, which again must be at least 36.
 */

void fill_inquiry_response(struct us_data *us, struct scsi_cmnd *srb,
		unsigned char *data, unsigned int data_len)
{
	if (data_len<36) // You lose.
		return;

	if(data[0]&0x20) { /* USB device currently not connected. Return
			      peripheral qualifier 001b ("...however, the
			      physical device is not currently connected
			      to this logical unit") and leave vendor and
			      product identification empty. ("If the target
			      does store some of the INQUIRY data on the
			      device, it may return zeros or ASCII spaces
			      (20h) in those fields until the data is
			      available from the device."). */
		memset(data+8,0,28);
	} else {
		u16 bcdDevice = us->pusb_dev->descriptor.bcdDevice;
		memcpy(data+8, us->unusual_dev->vendorName,
			strlen(us->unusual_dev->vendorName) > 8 ? 8 :
			strlen(us->unusual_dev->vendorName));
		memcpy(data+16, us->unusual_dev->productName,
			strlen(us->unusual_dev->productName) > 16 ? 16 :
			strlen(us->unusual_dev->productName));
		data[32] = 0x30 + ((bcdDevice>>12) & 0x0F);
		data[33] = 0x30 + ((bcdDevice>>8) & 0x0F);
		data[34] = 0x30 + ((bcdDevice>>4) & 0x0F);
		data[35] = 0x30 + ((bcdDevice) & 0x0F);
	}

	usb_stor_set_xfer_buf(data, data_len, srb);
}

/***********************************************************************
 * Device probing and disconnecting
 ***********************************************************************/

/* Associate our private data with the USB device */
static int associate_dev(struct us_data *us, struct usb_interface *intf)
{
	US_DEBUGP("-- %s\n", __FUNCTION__);

	/* Fill in the device-related fields */
	us->pusb_dev = intf->usb_dev;
	us->pusb_intf = intf;
	us->ifnum = intf->cur_altsetting->desc.bInterfaceNumber;
	US_DEBUGP("Vendor: 0x%04x, Product: 0x%04x, Revision: 0x%04x\n",
			us->pusb_dev->descriptor.idVendor,
			us->pusb_dev->descriptor.idProduct,
			us->pusb_dev->descriptor.bcdDevice);
	US_DEBUGP("Interface Subclass: 0x%02x, Protocol: 0x%02x\n",
			intf->cur_altsetting->desc.bInterfaceSubClass,
			intf->cur_altsetting->desc.bInterfaceProtocol);

	/* Store our private data in the interface */
	intf->private_data = us;

	/* Allocate the device-related DMA-mapped buffers */
	us->cr = usb_alloc_coherent(us->pusb_dev, sizeof(*us->cr), &us->cr_dma);
	if (!us->cr) {
		US_DEBUGP("usb_ctrlrequest allocation failed\n");
		return -ENOMEM;
	}

	us->iobuf = usb_alloc_coherent(us->pusb_dev, US_IOBUF_SIZE, &us->iobuf_dma);
	if (!us->iobuf) {
		US_DEBUGP("I/O buffer allocation failed\n");
		return -ENOMEM;
	}
	return 0;
}

/* Get the unusual_devs entries and the string descriptors */
static void get_device_info(struct us_data *us, int id_index)
{
	struct usb_device *dev = us->pusb_dev;
	struct usb_interface_descriptor *idesc =
		&us->pusb_intf->cur_altsetting->desc;
	struct us_unusual_dev *unusual_dev = &us_unusual_dev_list[id_index];
	struct usb_device_id *id = &storage_usb_ids[id_index];

	/* Store the entries */
	us->unusual_dev = unusual_dev;
	us->subclass = (unusual_dev->useProtocol == US_SC_DEVICE) ?
			idesc->bInterfaceSubClass :
			unusual_dev->useProtocol;
	us->protocol = (unusual_dev->useTransport == US_PR_DEVICE) ?
			idesc->bInterfaceProtocol :
			unusual_dev->useTransport;
	us->flags = unusual_dev->flags;

	/* Log a message if a non-generic unusual_dev entry contains an
	 * unnecessary subclass or protocol override.  This may stimulate
	 * reports from users that will help us remove unneeded entries
	 * from the unusual_devs.h table.
	 */
	if (id->idVendor || id->idProduct) {
		static char *msgs[3] = {
			"an unneeded SubClass entry",
			"an unneeded Protocol entry",
			"unneeded SubClass and Protocol entries"};
		struct usb_device_descriptor *ddesc = &dev->descriptor;
		int msg = -1;

		if (unusual_dev->useProtocol != US_SC_DEVICE &&
			us->subclass == idesc->bInterfaceSubClass)
			msg += 1;
		if (unusual_dev->useTransport != US_PR_DEVICE &&
			us->protocol == idesc->bInterfaceProtocol)
			msg += 2;
		if (msg >= 0)
			printf(USB_STORAGE "This device "
				"(%04x,%04x,%04x S %02x P %02x)"
				" has %s in unusual_devs.h\n",
				ddesc->idVendor,
				ddesc->idProduct,
				ddesc->bcdDevice,
				idesc->bInterfaceSubClass,
				idesc->bInterfaceProtocol,
				msgs[msg]);
	}
}

/* Get the transport settings */
static int get_transport(struct us_data *us)
{
	switch (us->protocol) {
	case US_PR_CB:
		us->transport_name = "Control/Bulk";
		us->transport = usb_stor_CB_transport;
		us->transport_reset = usb_stor_CB_reset;
		us->max_lun = 7;
		break;

	case US_PR_CBI:
		us->transport_name = "Control/Bulk/Interrupt";
		us->transport = usb_stor_CBI_transport;
		us->transport_reset = usb_stor_CB_reset;
		us->max_lun = 7;
		break;

	case US_PR_BULK:
		us->transport_name = "Bulk";
		us->transport = usb_stor_Bulk_transport;
		us->transport_reset = usb_stor_Bulk_reset;
		break;

	default:
		return -EIO;
	}

	printf("  Transport: %s\n", us->transport_name);
	return 0;
}

/* Get the protocol settings */
static int get_protocol(struct us_data *us)
{
	switch (us->subclass) {
	case US_SC_RBC:
		us->protocol_name = "Reduced Block Commands (RBC)";
		us->proto_handler = usb_stor_transparent_scsi_command;
		break;

	case US_SC_8020:
		us->protocol_name = "8020i";
		us->proto_handler = usb_stor_ATAPI_command;
		us->max_lun = 0;
		break;

	case US_SC_QIC:
		us->protocol_name = "QIC-157";
		us->proto_handler = usb_stor_qic157_command;
		us->max_lun = 0;
		break;

	case US_SC_8070:
		us->protocol_name = "8070i";
		us->proto_handler = usb_stor_ATAPI_command;
		us->max_lun = 0;
		break;

	case US_SC_SCSI:
		us->protocol_name = "Transparent SCSI";
		us->proto_handler = usb_stor_transparent_scsi_command;
		break;

	case US_SC_UFI:
		us->protocol_name = "Uniform Floppy Interface (UFI)";
		us->proto_handler = usb_stor_ufi_command;
		break;

	default:
		return -EIO;
	}

	printf("  Protocol: %s\n", us->protocol_name);
	return 0;
}

/* Get the pipe settings */
static int get_pipes(struct us_data *us)
{
	struct usb_host_interface *altsetting =
		us->pusb_intf->cur_altsetting;
	int i;
	struct usb_endpoint_descriptor *ep;
	struct usb_endpoint_descriptor *ep_in = NULL;
	struct usb_endpoint_descriptor *ep_out = NULL;
	struct usb_endpoint_descriptor *ep_int = NULL;

	/*
	 * Find the endpoints we need.
	 * We are expecting a minimum of 2 endpoints - in and out (bulk).
	 * An optional interrupt is OK (necessary for CBI protocol).
	 * We will ignore any others.
	 */
	for (i = 0; i < altsetting->desc.bNumEndpoints; i++) {
		ep = &altsetting->endpoint[i].desc;

		/* Is it a BULK endpoint? */
		if ((ep->bmAttributes & USB_ENDPOINT_XFERTYPE_MASK)
				== USB_ENDPOINT_XFER_BULK) {
			/* BULK in or out? */
			if (ep->bEndpointAddress & USB_DIR_IN)
				ep_in = ep;
			else
				ep_out = ep;
		}

		/* Is it an interrupt endpoint? */
		else if ((ep->bmAttributes & USB_ENDPOINT_XFERTYPE_MASK)
				== USB_ENDPOINT_XFER_INT) {
			ep_int = ep;
		}
	}

	if (!ep_in || !ep_out || (us->protocol == US_PR_CBI && !ep_int)) {
		printf(USB_STORAGE "Endpoint sanity check failed! Rejecting dev.\n");
		return -EIO;
	}

	/* Calculate and store the pipe values */
	us->send_ctrl_pipe = usb_sndctrlpipe(us->pusb_dev, 0);
	us->recv_ctrl_pipe = usb_rcvctrlpipe(us->pusb_dev, 0);
	us->send_bulk_pipe = usb_sndbulkpipe(us->pusb_dev,
		ep_out->bEndpointAddress & USB_ENDPOINT_NUMBER_MASK);
	us->recv_bulk_pipe = usb_rcvbulkpipe(us->pusb_dev,
		ep_in->bEndpointAddress & USB_ENDPOINT_NUMBER_MASK);
	if (ep_int) {
		us->recv_intr_pipe = usb_rcvintpipe(us->pusb_dev,
			ep_int->bEndpointAddress & USB_ENDPOINT_NUMBER_MASK);
		us->ep_bInterval = ep_int->bInterval;
	}
	return 0;
}

static void usb_stor_acquire_resources(struct us_data *us)
{
	int p;

	/* Lock the device while we carry out the next two operations */
	mutex_lock(&us->dev_mutex);

	us->max_lun = 0;

	/* not single-lun devices */
	if (!(us->flags & US_FL_SINGLE_LUN)) {
		/* For bulk-only devices, determine the max LUN value */
		if (us->protocol == US_PR_BULK) {
			p = usb_stor_Bulk_max_lun(us);
			if (p < 0) {
				printf("  USB Mass Storage Get Max LUN fail\n");
				mutex_unlock(&us->dev_mutex);
				return;
			}

			/* check max lun data */
			if (p < USB_STORAGE_MAX_LUNS)
				us->max_lun = p;
			else
				us->max_lun = USB_STORAGE_MAX_LUNS - 1;
		}
	}

	mutex_unlock(&us->dev_mutex);

	printf("  USB Mass Storage Max LUN %d\n", us->max_lun);
}

/* Release all our dynamic resources */
static void usb_stor_release_resources(struct us_data *us)
{
	US_DEBUGP("-- %s\n", __FUNCTION__);

	if (us->current_urb)
		usb_free_urb(us->current_urb);
}

/* Dissociate from the USB device */
static void dissociate_dev(struct us_data *us)
{
	US_DEBUGP("-- %s\n", __FUNCTION__);

	/* Free the device-related DMA-mapped buffers */
	if (us->cr)
		usb_free_coherent(us->pusb_dev, sizeof(*us->cr), us->cr);

	if (us->iobuf)
		usb_free_coherent(us->pusb_dev, US_IOBUF_SIZE, us->iobuf);

	/* Remove our private data from the interface */
	us->pusb_intf->private_data = NULL;
}

#define MAX_SCSI_DEVICE_CODE 14
static const char *const scsi_device_types[MAX_SCSI_DEVICE_CODE] = {
	"Direct-Access    ",
	"Sequential-Access",
	"Printer          ",
	"Processor        ",
	"WORM             ",
	"CD-ROM           ",
	"Scanner          ",
	"Optical Device   ",
	"Medium Changer   ",
	"Communications   ",
	"Unknown          ",
	"Unknown          ",
	"RAID             ",
	"Enclosure        ",
};

static int storage_device_parse_inquiry(struct usb_storage_device *dev, unsigned char *inquiry_buf, u8 size)
{
	u8 dev_type;

	assert(dev);
	assert(inquiry_buf);
	assert(size >= SCSI_INQUIRY_BUFFERSIZE);

	dev_type = inquiry_buf[0] & 0x1f;

	memcpy(dev->vendor, &inquiry_buf[8], USB_STORAGE_INQUIRY_VENDOR_LEN);
	dev->vendor[USB_STORAGE_INQUIRY_VENDOR_LEN] = 0;

	memcpy(dev->product, &inquiry_buf[16], USB_STORAGE_INQUIRY_PRODUCT_LEN);
	dev->product[USB_STORAGE_INQUIRY_PRODUCT_LEN] = 0;

	memcpy(dev->version, &inquiry_buf[32], USB_STORAGE_INQUIRY_VERSION_LEN);
	dev->version[USB_STORAGE_INQUIRY_VERSION_LEN] = 0;

	printf("  Vendor: %s\n", dev->vendor);
	printf("  Product: %s\n", dev->product);
	printf("  Version: %s\n", dev->version);

	printf("  Type:   %s ",
	       dev_type < MAX_SCSI_DEVICE_CODE ? scsi_device_types[dev_type] :
	       "Unknown          ");
	printf("  ANSI SCSI revision: %02x", inquiry_buf[2] & 0x07);
	if ((inquiry_buf[2] & 0x07) == 1 && (inquiry_buf[3] & 0x0f) == 1)
		printf(" CCS\n");
	else
		printf("\n");

	printf("  Removable: %d\n", (inquiry_buf[1] & 0x80) >> 7);

	return 0;
}

static int storage_device_parse_capacity(struct usb_storage_device *dev, unsigned char *capacity_buf, u8 size)
{
	assert(dev);
	assert(capacity_buf);
	assert(size >= SCSI_CAPACITY_BUFFERSIZE);

	if (capacity_buf[0] == 0xff && capacity_buf[1] == 0xff &&
		capacity_buf[2] == 0xff && capacity_buf[3] == 0xff) {
		printf(USB_STORAGE "very big device.\n");
	}

	dev->block_count = 1 + (((u32)capacity_buf[0] << 24) | (capacity_buf[1] << 16) |
			(capacity_buf[2] << 8) | capacity_buf[3]);

	dev->block_size = (capacity_buf[4] << 24) |
		(capacity_buf[5] << 16) | (capacity_buf[6] << 8) | capacity_buf[7];

	if (dev->block_size == 0) {
		dev->block_size = 512;
		printf(USB_STORAGE "sector size 0 reported, assuming 512.\n");
	}

	if (dev->block_size != 512 && dev->block_size != 1024 &&
			dev->block_size != 2048 && dev->block_size != 4096) {
		printf(USB_STORAGE "unsupported block size %d\n", dev->block_size);
		return -EINVAL;
	}

	printf("  Block Size %d, Block Count %lld\n", dev->block_size, dev->block_count);

	return 0;
}

static void usb_stor_scan_work(void *data)
{
	int i;
	int result;
	struct usb_storage_device *dev;
	unsigned char buf[SCSI_INQUIRY_BUFFERSIZE];
	struct us_data *us = data;

	/* get max logic unit number */
	usb_stor_acquire_resources(us);

	for (i = 0; i <= us->max_lun; i++) {
		dev = &us->storage_device[i];
		dev->index = i;
		dev->user_data = NULL;
		dev->private_data = us;
		thread_waiter_init(&dev->unbind_wait);

		/* get manufacturer information */
		result = usb_stor_scsi_inquiry(us, i, buf, sizeof(buf));
		if (result)
			continue;

		/* parse inquiry buf to storage device */
		result = storage_device_parse_inquiry(dev, buf, sizeof(buf));
		if (result)
			continue;

		/* test lun ready */
		result = usb_stor_scsi_test_unit_ready(us, i);
		if (result)
			continue;

		/* read lun block_size and block_count */
		result = usb_stor_scsi_read_capacity(us, i, buf, sizeof(buf));
		if (result)
			continue;

		/* parse capacity buf to storage device */
		result = storage_device_parse_capacity(dev, buf, sizeof(buf));
		if (result)
			continue;

		/* new storage device */
		dev->bind_flag = USB_STORAGE_BIND_FLAG;
		result = usb_host_mass_storage_link_bind(dev);
		if (result) {
			dev->bind_flag = 0;
			continue;
		}
	}

	thread_waiter_wakeup(&us->exit_wait);
}

/* Probe to see if we can drive a newly-connected USB device */
static int storage_probe(struct usb_interface *intf,
			 const struct usb_device_id *id)
{
	struct us_data *us;
	const int id_index = id - storage_usb_ids;
	int result;

	US_DEBUGP("USB Mass Storage device detected\n");

	us = malloc(sizeof(struct us_data));
	if (!us) {
		printf(USB_STORAGE "Unable to allocate the device\n");
		return -ENOMEM;
	}
	memset(us, 0, sizeof(struct us_data));
	mutex_init(&(us->dev_mutex));
	thread_waiter_init(&us->exit_wait);

	/* Associate the us_data structure with the USB device */
	result = associate_dev(us, intf);
	if (result)
		goto BadDevice;

	/*
	 * Get the unusual_devs entries and the descriptors
	 *
	 * id_index is calculated in the declaration to be the index number
	 * of the match from the usb_device_id table, so we can find the
	 * corresponding entry in the private table.
	 */
	get_device_info(us, id_index);

	/* Get the transport, protocol, and pipe settings */
	result = get_transport(us);
	if (result)
		goto BadDevice;
	result = get_protocol(us);
	if (result)
		goto BadDevice;
	result = get_pipes(us);
	if (result)
		goto BadDevice;

	us->current_urb = usb_alloc_urb(0);
	if (!us->current_urb) {
		US_DEBUGP("URB allocation failed\n");
		result = -ENOMEM;
		goto BadDevice;
	}

	thread_create("usb_stor_scan_work", 4096, usb_stor_scan_work, us);

	return 0;

	/* We come here if there are any problems */
BadDevice:
	US_DEBUGP("storage_probe() failed\n");
	set_bit(US_FLIDX_DISCONNECTING, &us->flags);
	usb_stor_release_resources(us);
	dissociate_dev(us);
	free(us);
	return result;
}

/* Handle a disconnect event from the USB core */
static void storage_disconnect(struct usb_interface *intf)
{
	int i;
	int ret;
	struct usb_storage_device *dev;
	struct us_data *us = intf->private_data;

	US_DEBUGP("storage_disconnect() called\n");

	/* Prevent new USB transfers, stop the current command, and
	 * interrupt a SCSI-scan or device-reset delay */
	set_bit(US_FLIDX_DISCONNECTING, &us->flags);

	/* wait scan_work complete_exit */
	thread_waiter_wait(&us->exit_wait);

	/* Wait for the current command to finish, then remove the host */
	mutex_lock(&us->dev_mutex);
	mutex_unlock(&us->dev_mutex);

	for (i = 0; i <= us->max_lun; i++) {
		dev = &us->storage_device[i];
		if (dev->bind_flag) {
			assert(dev->bind_flag == USB_STORAGE_BIND_FLAG);
			usb_host_mass_storage_unlink(dev);

			/* wait mass storage unbind */
			ret = thread_waiter_wait_timeout(&dev->unbind_wait, USB_STORAGE_UNBIND_WAIT_TIMEOUT);
			if (ret) {
				dev->bind_flag = 0;
				dev->user_data = NULL;
				printf(USB_STORAGE "ERROR !!! unbind timeout, force unbind.\n");
			}
		}
	}

	/* Wait for the current command to finish, then remove the host */
	mutex_lock(&us->dev_mutex);
	mutex_unlock(&us->dev_mutex);

	/* Wait for everything to become idle and release all our resources */
	usb_stor_release_resources(us);
	dissociate_dev(us);

	free(us);
}

void usb_host_mass_storage_unbind(struct usb_storage_device *dev)
{
	assert(dev);
	assert(dev->bind_flag == USB_STORAGE_BIND_FLAG);

	dev->bind_flag = 0;
	thread_waiter_wakeup(&dev->unbind_wait);
}


int usb_host_mass_storage_write(struct usb_storage_device *dev, u8 *buffer, u32 sector, u16 count)
{
	assert(dev && buffer);

	if (count == 0)
		return 0;

	assert(dev->private_data);
	assert(dev->index < USB_STORAGE_MAX_LUNS);
	assert(dev->bind_flag == USB_STORAGE_BIND_FLAG);

	return usb_stor_scsi_write10(dev->private_data, dev->index, dev->block_size, buffer, sector, count);
}

int usb_host_mass_storage_read(struct usb_storage_device *dev, u8 *buffer, u32 sector, u16 count)
{
	assert(dev && buffer);

	if (count == 0)
		return 0;

	assert(dev->private_data);
	assert(dev->index < USB_STORAGE_MAX_LUNS);
	assert(dev->bind_flag == USB_STORAGE_BIND_FLAG);

	/* todo ... if fail try to use read6 */
	return usb_stor_scsi_read10(dev->private_data, dev->index, dev->block_size, buffer, sector, count);
}

static struct usb_driver usb_storage_driver = {
	.name =		"usb-storage",
	.probe =	storage_probe,
	.disconnect =	storage_disconnect,
	.id_table =	storage_usb_ids,
};

void usb_mass_storage_driver_register(void)
{
	usb_register_driver(&usb_storage_driver);
}

void usb_mass_storage_driver_deregister(void)
{
	usb_deregister(&usb_storage_driver);
}
