
CFLAGS += -Wno-unused-function
CFLAGS += -Ifilesystem/yaffs -Ifilesystem/yaffs/direct

src-y += dfs_yaffs_s.c
src-y += yaffs_flashif.c
src-y += yaffs_osglue.c

src-y += yaffs/yaffs_allocator.c
src-y += yaffs/yaffs_bitmap.c
src-y += yaffs/yaffs_checkptrw.c
src-y += yaffs/yaffs_ecc.c
src-y += yaffs/yaffs_endian.c
src-y += yaffs/yaffs_guts.c
src-y += yaffs/yaffs_nameval.c
src-y += yaffs/yaffs_nand.c
src-y += yaffs/yaffs_packedtags1.c
src-y += yaffs/yaffs_packedtags2.c
src-y += yaffs/yaffs_summary.c
src-y += yaffs/yaffs_tagscompat.c
src-y += yaffs/yaffs_tagsmarshall.c
src-y += yaffs/yaffs_verify.c
src-y += yaffs/yaffs_yaffs1.c
src-y += yaffs/yaffs_yaffs2.c

src-y += yaffs/direct/yaffs_attribs.c
src-y += yaffs/direct/yaffs_error.c
src-y += yaffs/direct/yaffs_hweight.c
src-y += yaffs/direct/yaffsfs.c
