src-$(CONFING_GSL1680_TOUCH) += touch/gsl1680/gsl1680_point.c touch/gsl1680/gsl1680_touch.c
src-$(CONFING_FT6236_TOUCH) += touch/ft6236/ft6236_touch.c
src-$(CONFIG_GT9XX_TOUCH) += touch/gt9xx/gt9xx_touch.c
src-$(CONFIG_ADC_RTS_TOUCH) += touch/resistance_touch/resistance_touch.c
