src-$(CONFIG_MMC) += mmc/mmc_devices.c

src-$(CONFIG_EMMC_DEVICE) += mmc/devices_emmc.c
src-$(CONFIG_EMMC_DEVICE) += mmc/mmc_partition.c
src-$(CONFIG_EMMC_DEVICE) += mmc/mmc_partition_parse_mbr_gpt.c

