
CFLAGS += -Ifilesystem/uffs -Ifilesystem/uffs/src/inc

src-y += dfs_uffs.c
src-y += uffs_nandif.c

src-y += src/uffs/uffs_badblock.c
src-y += src/uffs/uffs_blockinfo.c
src-y += src/uffs/uffs_buf.c
src-y += src/uffs/uffs_debug.c
src-y += src/uffs/uffs_device.c
src-y += src/uffs/uffs_ecc.c
src-y += src/uffs/uffs_fd.c
src-y += src/uffs/uffs_fs.c
src-y += src/uffs/uffs_init.c
src-y += src/uffs/uffs_mem.c
src-y += src/uffs/uffs_pool.c
src-y += src/uffs/uffs_public.c
src-y += src/uffs/uffs_tree.c
src-y += src/uffs/uffs_utils.c
src-y += src/uffs/uffs_mtb.c
src-y += src/uffs/uffs_find.c
src-y += src/uffs/uffs_flash.c
src-y += src/uffs/uffs_version.c
src-y += src/uffs/uffs_crc.c

src-y += src/platform/posix/uffs_os.c