src-y += late_init.c
src-$(CONFIG_CLK) += clk.c
src-$(CONFIG_SYSTICK) += systick.c
src-$(CONFIG_GPIO) += gpio.c
src-$(CONFIG_REGULATOR) += regulator.c
src-$(CONFIG_IRQ) += irq.c
src-$(CONFIG_UART) += uart.c
src-$(CONFIG_FB) += fb.c
src-$(CONFIG_HRTIMER) += hrtimer.c

src-$(CONFIG_CONSOLE) += console.c
src-$(CONFIG_UART_CONSOLE) += uart_console.c
src-$(CONFIG_CACHE) += cache.c
src-$(CONFIG_DMA) += dma.c
src-$(CONFIG_SPI) += spi.c
src-$(CONFIG_SSLV) += sslv.c
src-$(CONFIG_I2C) += i2c.c
src-$(CONFIG_RTC) += rtc.c
src-$(CONFIG_PWM) += pwm.c
src-$(CONFIG_ADC) += adc.c
src-$(CONFIG_AES) += aes.c
src-$(CONFIG_SECURITY_AES) += security_aes.c
src-$(CONFIG_HW_TIMER) += hw_timer.c
src-$(CONFIG_EFUSE) += efuse.c
src-$(CONFIG_WDT) += watchdog.c
src-$(CONFIG_SFC_NOR) += sfc_nor.c sfc_nor_partition.c
src-$(CONFIG_SFC_NAND) += sfc_nand.c sfc_nand_partition.c
src-$(CONFIG_CAMERA) += camera.c
src-$(CONFIG_ISP) += isp.c isp_tuning.c
src-$(CONFIG_ROTATOR) += rotator.c
src-$(CONFIG_PM) += pm.c
src-$(CONFIG_PCM) += pcm.c pcm_adapter.c pcm_mixer.c
src-$(CONFIG_BACKLIGHT) += backlight.c
src-$(CONFIG_CAN) += can.c

src-$(CONFIG_GPIO_PIN) += utils/gpio_pin.c
src-$(CONFIG_MEMORY_INHERIT) += utils/inherit.c

src-$(CONFIG_INPUT) += input.c

src-$(CONFIG_GPIO_SPI) += gpio_spi.c

src-$(CONFIG_GPIO_I2C) += gpio_i2c.c

src-$(CONFIG_LCD_GPIO) += slcd_gpio.c

src-$(CONFIG_MSCALER) += mscaler.c

src-$(CONFIG_DTRNG) += dtrng.c

src-$(CONFIG_DES) += des.c

src-$(CONFIG_MMC) += mmc.c

src-$(CONFIG_CONN) += conn.c

src-$(CONFIG_HASH) += hash.c

src-$(CONFIG_MAC) += mac.c

src-$(CONFIG_SCBOOT_DRIVER) += scboot.c

src-$(CONFIG_RTOS_OTA_UPDATE) += ota/ota.c ota/pkt.c ota/pkt_api.c ota/storage.c

src-$(CONFIG_OTA_AB_UPGRADE) += ota_ab_upgrade.c

obj-$(CONFIG_PWM_SCANNER) += drivers/pwm_scanner/pwm_scanner.o_shipped

src-$(CONFIG_PWM_AUDIO) += pwm_audio.c
