projectDir = 'D:\downloads\X2100_project-main\X2100_project-latest\matlab';
filePath = fullfile(projectDir, 'Record_20260814_161551_adc.dat');
addpath(projectDir);

cfg = x2100_default_config();
frame = x2100.io.readFrame(filePath, 1, cfg);
rangeProcessed = x2100.dsp.processRangeFrame(frame, cfg);
doppler = x2100.dsp.dopplerFft(rangeProcessed.rangeCube, cfg);
ddma = x2100.dsp.ddmaDecode(doppler.noncoherentMagnitude, cfg);

[peakAmplitude, linearIndex] = max(ddma.rdAmplitude, [], 'all');
[peakRange, peakSubDoppler] = ind2sub(size(ddma.rdAmplitude), linearIndex);
fprintf(['DDMA_PEAK range=%u subdoppler=%u amplitude=%.9g db=%.9g ' ...
    'best_subband=%u full_bin=%u metric=%.9g\n'], ...
    peakRange - 1, peakSubDoppler - 1, peakAmplitude, ...
    ddma.rdMapDb(linearIndex), ddma.bestSubband(linearIndex), ...
    ddma.decodedFullBin(linearIndex), ddma.bestMetric(linearIndex));

counts = zeros(1, cfg.stage3.numTotalSubbands);
for subband = 0:(cfg.stage3.numTotalSubbands - 1)
    counts(subband + 1) = nnz(ddma.bestSubband == subband);
end
fprintf('BEST_SUBBAND_COUNTS=');
fprintf('%u ', counts);
fprintf('\n');
fprintf('RD_SUM amplitude=%.9g energy=%.9g db_sum=%.9g metric_sum=%.9g\n', ...
    sum(ddma.rdAmplitude, 'all'), sum(ddma.rdAmplitude.^2, 'all'), ...
    sum(ddma.rdMapDb, 'all'), sum(ddma.bestMetric, 'all'));

selectedPairsZero = [ ...
    0 0; 0 7; 0 15; 0 31; ...
    7 0; 7 7; 7 15; 7 31; ...
    8 0; 8 7; 8 15; 8 31; ...
    31 3; 63 7; 127 15; 191 23; 255 31];
fprintf('DDMA_SELECTED=');
for k = 1:size(selectedPairsZero, 1)
    rangeBin = selectedPairsZero(k, 1);
    subDopplerBin = selectedPairsZero(k, 2);
    index = sub2ind(size(ddma.rdAmplitude), ...
        rangeBin + 1, subDopplerBin + 1);
    fprintf('{%u,%u,%u,%u,%.9g,%.9g,%.9g} ', ...
        rangeBin, subDopplerBin, ddma.bestSubband(index), ...
        ddma.decodedFullBin(index), ddma.rdAmplitude(index), ...
        ddma.rdMapDb(index), ddma.bestMetric(index));
end
fprintf('\n');
