
src-y += time_utils.c
src-$(CONFIG_OS_POSIX_PTHREAD) += pthread.c
src-$(CONFIG_OS_POSIX_PTHREAD_MUTEX) += pthread_mutex.c
src-$(CONFIG_OS_POSIX_PTHREAD_COND) += pthread_cond.c
src-$(CONFIG_OS_POSIX_PTHREAD_BARRIER) += pthread_barrier.c
src-$(CONFIG_OS_POSIX_SEM) += semaphore.c
src-$(CONFIG_OS_POSIX_MQEUEUE) += mqueue.c
src-$(CONFIG_OS_POSIX_TIMER) += timer.c
src-$(CONFIG_OS_POSIX_CLOCK) += clock.c
src-$(CONFIG_OS_POSIX_SCHED) += sched.c

