src-y += init.c

include devices/lcd/Makefile
include devices/backlight/Makefile
include devices/keyboard/Makefile
include devices/touch/Makefile
include devices/camera/Makefile
include devices/codec/Makefile
include devices/mmc/Makefile
include devices/ramdisk/Makefile
include devices/regulator/Makefile
include devices/afe/Makefile
include devices/cis/Makefile