src-y += task.c
src-$(CONFIG_XBURST2) += port_xburst2.c
src-$(CONFIG_XBURST) += port_xburst.c
src-y += test.c

src-y += wait_queue.c

src-y += os.c
src-y += thread.c
src-y += semaphore.c
src-y += thread_waiter.c
src-y += critical_thread_cond.c
src-y += thread_cond_and_mutex.c
