# TOPDIR = example/project/iscan/
TOPDIR:=

src-y += $(TOPDIR)iscan_example.c
src-y += $(TOPDIR)gadget_card_storage.c
src-y += $(TOPDIR)iscan_ui/iscan_thread_decode.c

src-y += $(TOPDIR)iscan_ui/iscan_ui.c
src-y += $(TOPDIR)iscan_ui/iscan_utils.c
src-y += $(TOPDIR)iscan_ui/iscan_view/menu_view.c
src-y += $(TOPDIR)iscan_ui/iscan_view/setting_view.c
src-y += $(TOPDIR)iscan_ui/iscan_view/languages_str.c
src-y += $(TOPDIR)iscan_ui/iscan_view/preview_view.c
src-y += $(TOPDIR)iscan_ui/iscan_view/message_box_view.c
src-y += $(TOPDIR)iscan_ui/iscan_view/scaning_view.c
src-y += $(TOPDIR)iscan_ui/iscan_view/usb_insert_view.c
src-y += $(TOPDIR)iscan_ui/iscan_view/calibrate_view.c
