src-$(CONFIG_ADC_KEYBOARD) += keyboard/adc_keyboard.c
src-$(CONFIG_GPIO_KEYBOARD) += keyboard/gpio_keyboard.c
src-$(CONFIG_MATRIX_KEYBOARD1) += keyboard/matrix_keyboard1.c
src-$(CONFIG_MATRIX_KEYBOARD2) += keyboard/matrix_keyboard2.c
src-$(CONFIG_MATRIX_KEYBOARD3) += keyboard/matrix_keyboard3.c
