#include "languages_str.h"

const char *STRING_TABLE[LANG_COUNT][STRID_COUNT] = {
{
        "Mode",
        "JPG/PDF",
        "JPG",
        "PDF - A4",
        "PDF - Letter",
        "Quality",
        "LO - 300DPI",
        "MI - 600DPI",
        "HI - 1050DPI",
        "HI - 1200DPI",
        "Color",
        "Color",
        "Mono",
        "Language",
        "English",
        "Français",
        "Español",
        "Deutsch",
        "Italiano",
        "繁體中文",
        "简体中文",
        "日本語",
        "Pусский",
        "Nederlands",
        "Date/Time",
        "Y",
        "M",
        "D",
        "H",
        "M",
        "Inst.Preview",
        "On",
        "Off",
        "Auto Off",
        "3 Min",
        "Off",
        "Delete All",
        "Delete all files?",
        "All files have been deleted!",
        "Delete this file?",
        "Delete?",
        "The file has been deleted!",
        "No File",
        "No Files",
        "Yes",
        "No",
        "Format",
        "Format the memory card?",
        "All files will be erased. ",
        "The memory card has been formatted!",
        "Device Info",
        "FW Version",
        "WiFi Name",
        "HTTP Add.",
        "New Firmware detected. Update?",
        "Firmware   update  in   progress!",
        "Update Completed! ",
        "Update Failed! ",
        "Insert a Memory card",
        "Failed! The file is protected!",
        "1. Calibration starts. Do not move the device!",
        "2. Scan the calibration sheet!",
        "3. Calibration completed!",
        "…",
        "Frequency ",
        "File size is too large to zoom",
        "",
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890~!@#$%^&*()-_=+[]{}|\\/:;'\",.<>?",
    },
    {
        "Modo",
        "JPG/PDF",
        "JPG",
        "PDF - A4",
        "PDF - Letter",
        "Calidad",
        "LO - 300DPI",
        "MI - 600DPI",
        "HI- 1050DPI",
        "HI - 1200DPI",
        "Color",
        "Color",
        "Mono",
        "Idioma",
        "English",
        "Français",
        "Español",
        "Deutsch",
        "Italiano",
        "繁體中文",
        "简体中文",
        "日本語",
        "Pусский",
        "Nederlands",
        "Fecha/Hora",
        "A",
        "M",
        "D",
        "H",
        "M",
        "Vista pr.ins.",
        "Encendido",
        "Apagado",
        "Apa.auto",
        "3 min.",
        "Apagado",
        "Borrar todo",
        "¿Borrar todos los archivos?",
        "¡Se han borrado los archivos!",
        "¿Borrar archivo?",
        "¿Borrar?",
        "¡Se ha borrado el archivo!",
        "Ningún archivo",
        "Ningún archive",
        "Sí",
        "No",
        "Formato",
        "¿Formatear la tarjeta de memoria?",
        "Se borrarán todos los archivos. ",
        "¡Tarjeta formateada!",
        "Info.disp.",
        "Versión FW",
        "Nombre de wifi",
        "Dirección HTTP",
        "Firmware nuevo detectado. ¿Actualizar?",
        "¡Actualización en curso! ¡",
        "¡Actualización realizada! ",
        "¡Actualización errónea! ",
        "Introducir tarjeta",
        "Error! El archivo está protegido",
        "1. Calibración se inicia. No mueva el dispositivo!",
        "2. Escanee la hoja de calibración!",
        "3. Calibración realizada!",
        "…",
        "Frecuencia",
        "Tamaño del archivo es demasiado grande para hacer un zoom",
        "",
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890~!@#$%^&*()-_=+[]{}|\\/:;'\",.<>?",
    },
    {
        "Mode",
        "JPG/PDF",
        "JPG",
        "PDF - A4",
        "PDF - Lettre",
        "Qualité",
        "LO - 300DPI",
        "MI - 600DPI",
        "HI - 1050DPI",
        "HI - 1200DPI",
        "Couleur",
        "Couleur",
        "Mono",
        "Langue",
        "English",
        "Français",
        "Español",
        "Deutsch",
        "Italiano",
        "繁體中文",
        "简体中文",
        "日本語",
        "Pусский",
        "Nederlands",
        "Date/Heure",
        "A",
        "M",
        "J",
        "H",
        "M",
        "Prév. Inst.",
        "Activé",
        "Désactivé",
        "Ar. Aut.",
        "3 Min",
        "Désactivé",
        "Effacer tout",
        "Supprimer tous les fichiers ?",
        "Les fichiers ont été supprimés !",
        "Supp. fichier ?",
        "Supp. ?",
        "Les fichiers ont été supprimées !",
        "Pas de fichier",
        "Pas de fichiers",
        "Oui",
        "Non",
        "Formatage",
        "Formatter la carte mémoire?",
        "Tous les fichiers seront supprimés.",
        "La carte mémoire a été formatée !",
        "Info Disp.",
        "Version FW",
        "Nom du Wifi",
        "Ajouter http.",
        "Nouv. logi. inte. MAJ ?",
        "Mise à jour du logiciel interne en cours !",
        "Mise à jour terminée !",
        "Échecs de mise jour ! ",
        "Insérer carte mém.",
        "Échec! Le fichier est protégé!",
        "1. Etalonnage commence. Ne bougez pas l'appareil!",
        "2. Numérisez la feuille d'étalonnage!",
        "3. Etalonnage terminée!",
        "…",
        "Fréquence",
        "Taille du fichier est trop volumineux pour zoomer\n",
        "",
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890~!@#$%^&*()-_=+[]{}|\\/:;'\",.<>?",
    },
    {
        "模式",
        "JPG/PDF",
        "JPG",
        "PDF - A4",
        "PDF - 信纸",
        "图象质量",
        "LO - 300DPI",
        "MI - 600DPI",
        "HI - 1050DPI",
        "HI - 1200DPI",
        "色彩",
        "彩色",
        "单色",
        "语言设置",
        "English",
        "Français",
        "Español",
        "Deutsch",
        "Italiano",
        "繁體中文",
        "简体中文",
        "日本語",
        "Pусский",
        "Nederlands",
        "日期/时间",
        "年",
        "月",
        "日",
        "时",
        "分",
        "即时预览",
        "开",
        "关",
        "自动关机",
        "3 分钟",
        "关",
        "删除全部",
        "删除全部文件？",
        "所有文件已被删除",
        "删除这个文件？",
        "删除？",
        "文件已被删除！",
        "没有文件",
        "没有文件",
        "是",
        "否",
        "格式化",
        "格式化存储卡？",
        "所有文件将被擦除",
        "存储卡已被格式化！",
        "设备信息",
        "固件版本",
        "WiFi名称",
        "http 地址",
        "侦测到新固件。",
        "固件正在更新中！",
        "更新成功！",
        "更新失败！",
        "插入一张存储卡",
        "失败，文件被保护",
        "校正开始，请勿操作",
        "开始扫描校正纸",
        "校正完成",
        "…",
        "频率",
        "文件超出大小",
        "",
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890~!@#$%^&*()-_=+[]{}|\\/:;'\",.<>?",
    },
    {
        "模式",
        "JPG/PDF",
        "JPG",
        "PDF - A4",
        "PDF - 信紙",
        "影像品質",
        "LO - 300DPI",
        "MI - 600DPI",
        "HI - 1050DPI",
        "HI - 1200DPI",
        "色彩效果",
        "彩色",
        "單色",
        "語系",
        "English",
        "Français",
        "Español",
        "Deutsch",
        "Italiano",
        "繁體中文",
        "简体中文",
        "日本語",
        "Pусский",
        "Nederlands",
        "日期/時間",
        "年",
        "月",
        "日",
        "時",
        "分",
        "即時預覽",
        "開",
        "關",
        "自動關機",
        "3 分鐘",
        "關",
        "刪除全部",
        "刪除全部文件？",
        "所有文件已被删除",
        "刪除這個文件？",
        "刪除？",
        "文件已被刪除！",
        "沒有文件",
        "沒有文件",
        "是",
        "否",
        "格式化",
        "格式化存儲卡？",
        "所有文件將被擦除",
        "存儲卡已被格式化",
        "設備信息",
        "固件版本",
        "Wifi名稱",
        "http 地址",
        "偵測到最新軟件",
        "軟件正在更新中！",
        "更新成功！",
        "更新失敗！",
        "插入一張存儲卡",
        "失敗，文件被保護",
        "校正開始，請勿操作",
        "開始掃描校正紙",
        "校正完成",
        "…",
        "頻率",
        "文件超出大小",
        "",
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890~!@#$%^&*()-_=+[]{}|\\/:;'\",.<>?",
    },
    {
        "Modus",
        "JPG/PDF",
        "JPG",
        "PDF - A4",
        "PDF - Letter ",
        "Qualität",
        "LO - 300DPI",
        "MI - 600DPI",
        "HI - 1050DPI",
        "HI - 1200DPI",
        "Farbe",
        "Farbe",
        "Mono",
        "Sprache",
        "English",
        "Français",
        "Español",
        "Deutsch",
        "Italiano",
        "繁體中文",
        "简体中文",
        "日本語",
        "Pусский",
        "Nederlands",
        "Datum/Uhrzeit",
        "J",
        "M",
        "T",
        "S",
        "M",
        "Vorschau",
        "An",
        "Aus",
        "AutoAbschalt",
        "3 Min",
        "Aus",
        "Alle löschen",
        "Alle Dateien löschen?",
        "Alle Dateien wurden gelöscht!",
        "Diese Datei löschen?",
        "Lösch?",
        "Die Datei wurde gelöscht!",
        "Keine Datei",
        "Keine Dateien",
        "Ja",
        "Ein",
        "Format",
        "Die\nSpeicherkarte formatieren?",
        "Alle Dateien werden gelöscht!",
        "Die Speicherkarte wurde formatiert?",
        "Geräte-Info",
        "FW-Version",
        "WiFi-Name",
        "Http-Adresse",
        "Neue Firmware vorhanden. Aktualisieren?",
        "Die Firmware wird aktualisiert! ",
        "Aktualisierung abgeschlossen! ",
        "Aktualisierung fehlgeschlagen!",
        "Speicherkarte einsetzen",
        "Fehlgeschlagen! Die Datei ist schreibgeschützt!",
        "Die Kalibrierung läuft. Das Gerät nicht bewegen!",
        "2. Das Kalibrierungsblatt wird gescannt!",
        "3. Kalibrierung abgeschlossen!",
        "…",
        "Frequenz",
        "Die Datei ist zum Zoomen zu groß",
        "",
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890~!@#$%^&*()-_=+[]{}|\\/:;'\",.<>?",
    },
    {
        "Modalità",
        "JPG/PDF",
        "JPG",
        "PDF - A4",
        "PDF - Lettera ",
        "Qualità",
        "LO - 300DPI",
        "MI - 600DPI",
        "HI - 1050DPI",
        "HI - 1200DPI",
        "Colore",
        "Colore",
        "Mono",
        "Lingua",
        "English",
        "Français",
        "Español",
        "Deutsch",
        "Italiano",
        "繁體中文",
        "简体中文",
        "日本語",
        "Pусский",
        "Nederlands",
        "Data/Ora",
        "A",
        "M",
        "G",
        "O",
        "M",
        "Anteprima ist.",
        "On",
        "OFF",
        "Spegn. autom.",
        "3 Min",
        "OFF",
        "Elimina tutto",
        "Eliminare tutti i file?",
        "Sono stati eliminati tutti i file!",
        "Eliminare questo file?",
        "Elim.",
        "Il file è stato eliminato!",
        "Nessun file",
        "Nessun file",
        "Sì",
        "No",
        "Formattazione",
        "Formattare la scheda di memoria?",
        "Tutti i file saranno cancellati.",
        "La scheda di memoria è stata formattata!",
        "Info dispositivo",
        "Versione FW",
        "Nome del WiFi",
        "Indirizzo HTTP",
        "Rilevato nuovo firmware. Aggiornare?",
        "Aggiornamento firmware in corso. ",
        "Aggiornamento completato! ",
        "Aggiornamento non riuscito!",
        "Ins. scheda memoria.",
        "Errore! Il file è protetto!",
        "Avvio calibrazione. Non spostare il dispositivo!",
        "2. Scansionare il foglio di calibrazione!",
        "3. Calibrazione completata!",
        "…",
        "Frequenza",
        "Dimensioni del file troppo grandi per effettuare lo zoom",
        "",
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890~!@#$%^&*()-_=+[]{}|\\/:;'\",.<>?",
    },
    {
        "режим",
        "JPG/PDF",
        "JPG",
        "PDF - A4",
        "PDF -Конверт",
        "качество ",
        "LO - 300DPI",
        "MI - 600DPI",
        "HI - 1050DPI",
        "HI - 1200DPI",
        "Цветной",
        "Цветной",
        "Градации серого",
        "Язык",
        "English",
        "Français",
        "Español",
        "Deutsch",
        "Italiano",
        "繁體中文",
        "简体中文",
        "日本語",
        "Pусский",
        "Nederlands",
        "Дата / время",
        "Г",
        "М",
        "Д",
        "ч",
        "м",
        "Предпросм.",
        "Вкл.",
        "Выкл.",
        "Авто-выкл",
        "3 мин.",
        "Выкл.",
        "Удалить все",
        "Удалить все файлы?",
        "Все файлы удалены!",
        "Удалить файл?",
        "Убрать?",
        "Файл удален!",
        "Нет файла",
        "Нет файлов",
        "Да",
        "Нет",
        "Формат",
        "Освоб.карту?",
        "Все файлы будут удалены!",
        "Карта свободна!",
        "Информ.",
        "Версия",
        "Имя для WiFi",
        "Адрес HTTP",
        "Есть новая версия. Обновляемся?",
        "Идет обновление программы! ",
        "Обновление окончено! ",
        "Обновление неудачно! ",
        "Вставьте карту памяти",
        "Ошибка! Файл защищен от удаления!",
        "Идет калибровка. Не двигайте устройство!",
        "2. Отсканируйте калибровочный образец.",
        "3. Калибровка окончена!",
        "…",
        "Частота",
        "Слишком велик размер файла для увеличения масштаба.",
        "",
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890~!@#$%^&*()-_=+[]{}|\\/:;'\",.<>?",
    },
    {
        "モード",
        "JPG/PDF",
        "JPG",
        "PDF - A4",
        "PDF - Letter ",
        "画質",
        "LO - 300DPI",
        "MI - 600DPI",
        "HI - 1050DPI",
        "HI - 1200DPI",
        "カラー",
        "カラー",
        "モノ",
        "言語",
        "English",
        "Français",
        "Español",
        "Deutsch",
        "Italiano",
        "繁體中文",
        "简体中文",
        "日本語",
        "Pусский",
        "Nederlands",
        "日/時刻",
        "年",
        "月",
        "日",
        "時",
        "分",
        "即時プレビュー",
        "オン",
        "オフ",
        "自動オフ",
        "3 分",
        "オフ",
        "すべて消去",
        "全ファイル消去？",
        "全ファイル消去",
        "ファイルを消去？",
        "消去しますか？",
        "ファイル消去完了",
        "ファイルなし",
        "ファイルなし",
        "はい",
        "いいえ",
        "初期化",
        "メモリ初期化？",
        "全ファイル消去",
        "メモリ初期化完了",
        "デバイス情報",
        "バージョン",
        "WiFi名",
        "HTTPアドレス",
        "新しいFWに更新？",
        "FWの更新中",
        "更新が完了しました。",
        "更新に失敗しました。",
        "メモリカード挿入",
        "保護されたファイル",
        "1較正のため静止",
        "2較正シートスキャン",
        "3較正完了",
        "…",
        "周波数",
        "ズームできません",
        "",
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890~!@#$%^&*()-_=+[]{}|\\/:;'\",.<>?",
    },
    {
        "Modus",
        "JPG/PDF",
        "JPG",
        "PDF - A4",
        "PDF - Letter",
        "Kwaliteit",
        "LO - 300DPI",
        "MI - 600DPI",
        "HI - 1050DPI",
        "HI - 1200DPI",
        "Kleur",
        "Kleur",
        "Mono",
        "Taal",
        "English",
        "Français",
        "Español",
        "Deutsch",
        "Italiano",
        "繁體中文",
        "简体中文",
        "日本語",
        "Pусский",
        "Nederlands",
        "Datum/Tijd",
        "J",
        "M",
        "D",
        "U",
        "M",
        "Preview",
        "Aan",
        "Uit",
        "Auto Uit",
        "3 Mins",
        "Uit",
        "Alles Wissen",
        "Alle bestanden wissen?",
        "Alle bestanden zijn gewist!",
        "Dit bestand wissen?",
        "Wissen",
        "Het bestand is gewist!",
        "Geen bestand",
        "Geen bestanden",
        "Ja",
        "Nee",
        "Formatteren",
        "De geheugenkaart formatteren?",
        "Alle bestanden zullen worden gewist.",
        "Geformatt.",
        "Apparaat Info",
        "FW Versie",
        "WiFi Naam",
        "HTTP Toevoegen",
        "Firmware. Update?",
        "Update loopt! Niet uitschakelen!",
        "Update Voltooid!",
        "Update Mislukt! ",
        "Steek een Kaart in",
        "Milsukt! Het bestand is beveiligd!",
        "Kalibratie start. Beweeg het apparaat niet!",
        "2. Scan het kalibratievel!",
        "3. Kalibratie voltooid!",
        "…",
        "Frequentie",
        "Bestandgrootte is te groot om te zoomen",
        "",
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890~!@#$%^&*()-_=+[]{}|\\/:;'\",.<>?",
    },
};
