#ifndef __LANGUAGES_STR_H__
#define __LANGUAGES_STR_H__


#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    STRID_MODE = 0,
    STRID_FILE_FORMAT,
    STRID_JPG_FILE,
    STRID_PDF_A4_SIZE,
    STRID_PDF_LETTER_FILE,
    STRID_QUALITY,
    STRID_LOW_300DPI,
    STRID_HIGH_600DPI,
    STRID_FINE_1050DPI,
    STRID_FINE_1200DPI,
    STRID_COLOR_MODE,
    STRID_COLOR_COLOR,
    STRID_COLOR_MONO,
    STRID_LANGUAGE,
    STRID_LANG_EN,
    STRID_LANG_FR,
    STRID_LANG_ES,
    STRID_LANG_DE,
    STRID_LANG_IT,
    STRID_LANG_TC,
    STRID_LANG_SC,
    STRID_LANG_JP,
    STRID_LANG_RU,
    STRID_LANG_DU,
    STRID_DATE_TIME,
    STRID_Y,
    STRID_M,
    STRID_D,
    STRID_H,
    STRID_MI,
    STRID_INSTANT_PREVIEW,
    STRID_ON,
    STRID_OFF,
    STRID_AUTO_OFF,
    STRID_AUTO_OFF_3MIN,
    STRID_AUTO_OFF_SUB,
    STRID_DELETE_ALL,
    STRID_DELETE_ALL_FILEES,
    STRID_HAVE_BEEN_DELETED,
    STRID_DELETE_THIS_FILEES,
    STRID_DELETE,
    STRID_HAS_BEEN_DELETED,
    STRID_NO_FILE,
    STRID_NO_FILES,
    STRID_YES,
    STRID_NO,
    STRID_FORMAT,
    STRID_FORMAT_MEMORY,
    STRID_ARE_YOU_SURE,
    STRID_HAS_BEEN_FORMAT,
    STRID_DEVICE_INFO,
    STRID_FW_VERSION,
    STRID_WIFI_NAME,
    STRID_HTTP_ADD,
    STRID_FW_UPDATE,
    STRID_FW_UPDATE_PROGRESS,
    STRID_FW_UPDATE_COMPLETED,
    STRID_FW_UPDATE_FALSED,
    STRID_INSERT_CARD,
    STRID_FILE_PROTECT,
    STRID_CAL_START,
    STRID_CAL_SHEET,
    STRID_CAL_COMPLETE,
    STRID_CAL,
    STRID_FREQUENCY,
    STRID_SIZE_TOO_LARGE,
    STRID_NULL,
    STRID_DUMMY,
    STRID_COUNT
} StringId;

enum iscan_languags {
    LANG_EN = 0,
    LANG_ES,
    LANG_FR,
    LANG_SC,
    LANG_TC,
    LANG_DE,
    LANG_IT,
    LANG_RU,
    LANG_JP,
    LANG_DU,
    LANG_COUNT
};


extern const char*  STRING_TABLE[LANG_COUNT][STRID_COUNT];

#ifdef __cplusplus
}
#endif


#endif