


src-y += ingenic_phy_clk.c

src-$(CONFIG_X2000_MAC0) += ingenic_mac0_device.c
src-$(CONFIG_X2000_MAC1) += ingenic_mac1_device.c

src-y += stmmac_main.c stmmac_mdio.c ring_mode.c	\
			chain_mode.c dwmac_lib.c dwmac1000_core.c  dwmac1000_dma.c \
			enh_desc.c  norm_desc.c mmc_core.c
