#include <relocate.h>
#include <stdio.h>

void relocate_got(struct relocate_header *head, unsigned long new_start)
{
    int relocate_offset = new_start - head->start;
    int *got = (int *)(head->got_start + relocate_offset);
    int i;

    /*
    * Now we want to update GOT.
    *
    * GOT[0] is reserved.
    * GOT[1] is also reserved for the dynamic object
    * generated by GNU ld. Skip these reserved entries from relocation.
    */
    for (i = 2; i < head->num_got_entries; i++) {
        if (got[i] != 0)
            got[i] += relocate_offset;
    }

    unsigned int *rel = (unsigned int *)(head->rel_dyn_start + relocate_offset);
    unsigned int *rel_end = (unsigned int *)(head->rel_dyn_end + relocate_offset);

    /*
     * 跳过第一个保留的位置,
     * 每个 rel.dyn entry的大小是2个word
     */
    for (rel += 2; rel < rel_end; rel += 2) {
        /*
         * 跳过 非 R_MIPS_REL32 的位置
         */
        if (rel[1] == 3) {
            unsigned int *p = (unsigned int *)(rel[0] + relocate_offset);
            p[0] += relocate_offset;
        }
    }
}

void dump_relocate_header(struct relocate_header *head)
{
    printf("version         : %08lx\n", head->version);
    printf("start           : %08lx\n", head->start);
    printf("gp              : %08lx\n", head->gp);
    printf("rel_dyn_start   : %08lx\n", head->rel_dyn_start);
    printf("rel_dyn_end     : %08lx\n", head->rel_dyn_end);
    printf("image_copy_end  : %08lx\n", head->image_copy_end);
    printf("num_got_entries : %08lx\n", head->num_got_entries);
    printf("got_start       : %08lx\n", head->got_start);
    printf("ram_size        : %08lx\n", head->ram_size);
    printf("entry           : %08lx\n", head->entry);
}