projectDir = 'D:\downloads\X2100_project-main\X2100_project-latest\matlab';
filePath = fullfile(projectDir, 'Record_20260814_161551_adc.dat');
addpath(projectDir);

cfg = x2100_default_config();
frame = x2100.io.readFrame(filePath, 1, cfg);
rangeProcessed = x2100.dsp.processRangeFrame(frame, cfg);
doppler = x2100.dsp.dopplerFft(rangeProcessed.rangeCube, cfg);
ddma = x2100.dsp.ddmaDecode(doppler.noncoherentMagnitude, cfg);
cfar = x2100.detection.firmwareCfar2d(ddma.rdMapDb, cfg);
detections = x2100.detection.extractDetections(ddma.rdMapDb, cfar, ddma, cfg);
angle = x2100.detection.estimateAngles( ...
    detections, doppler.dopplerCube, ddma, cfg, cfg.stage4.angleCalibration);
post = x2100.postprocess.processDetections(angle.detections, cfg);

fprintf(['POINT_CONSTANTS range_res=%.12g doppler_res=%.12g wrap=%.12g ' ...
    'install_angle=%.9g static_threshold=%.9g\n'], ...
    cfg.axes.rangeBinM, cfg.axes.velocityBinMps, ...
    cfg.stage3.velocityWrapThresholdMps, cfg.stage5.installAngleDeg, ...
    cfg.stage5.staticVelocityThresholdMps);

fprintf('POINT_RAW=%u\n', numel(angle.detections));
for k = 1:numel(angle.detections)
    det = angle.detections(k);
    fprintf(['POINT%u r=%u d=%u sb=%u rawd=%g decd=%g rinterp=%.9g ' ...
        'range=%.9g velocity=%.9g azimuth=%.9g x=%.9g y=%.9g ' ...
        'power=%.9g snr=%.9g ispeak=%u\n'], ...
        k - 1, det.rangeBin, det.subDopplerBin, det.selectedSubband, ...
        det.fullDopplerBinRaw, det.dopplerBinDecoded, ...
        det.rangeBinInterpolated, det.rangeM, det.velocityMps, ...
        det.azimuthDeg, det.xM, det.yM, det.powerDb, det.snrDb, det.isPeak);
end

c = post.rejectionCounts;
fprintf(['POST_COUNTS input=%u valid=%u rejected=%u angle=%u bounce=%u ' ...
    'near=%u ground=%u verynear=%u\n'], ...
    c.input, c.valid, c.rejected, c.largeAngle, c.bouncing, ...
    c.nearLowPower, c.weakMovingGround, c.veryNear);
for k = 1:numel(post.allDetections)
    det = post.allDetections(k);
    fprintf(['POST%u range=%.9g vamb=%.9g vground=%.9g azimuth=%.9g ' ...
        'xout=%.9g yout=%.9g motion=%u mask=0x%02x valid=%u\n'], ...
        k - 1, det.rangeM, det.velocityAmbiguousMps, ...
        det.velocityGroundMps, det.azimuthDeg, det.xOutputM, ...
        det.yOutputM, det.motionState, det.rejectionMask, det.isValid);
end
