src-$(CONFIG_IRQ) += irq.c
src-$(CONFIG_CLK) += clk_source.c
src-$(CONFIG_CLK) += clk_gate.c
src-$(CONFIG_CLK) += clk.c
src-$(CONFIG_CLK) += clk_cgu.c
src-$(CONFIG_CLK) += i2s_cgu.c
src-$(CONFIG_CLK) += i2s_child_clk.c
src-$(CONFIG_CLK) += clk_pll.c
src-$(CONFIG_CLK) += clk_cpccr.c
src-$(CONFIG_SYSTICK) += ost_timer.c
src-$(CONFIG_GPIO) += gpio.c
src-$(CONFIG_UART) += uart.c
src-$(CONFIG_DMA) += dma.c
src-$(CONFIG_X2000_SPI0) += spi.c
src-$(CONFIG_X2000_SPI1) += spi.c
src-$(CONFIG_I2C) += i2c.c
src-y += rtc.c
src-y += init.c
src-$(CONFIG_PWM) += pwm.c
src-$(CONFIG_EFUSE_MODE_NONE) += efuse.c
src-$(CONFIG_EFUSE_MODE_HAMMING) += efuse_hamming.c
src-$(CONFIG_WDT) += watchdog.c
src-$(CONFIG_ADC) += adc.c hal/adc_hal.c
src-$(CONFIG_AES) += aes.c hal/aes_hal.c
src-$(CONFIG_DTRNG) += dtrng.c
src-$(CONFIG_HASH) += hash.c
src-$(CONFIG_USB_DRIVER) += cpm_usb.c

src-$(CONFIG_X2000_LCD) += lcdc.c

src-$(CONFIG_X2000_UTILS_RTC32K) += rtc32k_out.c

src-$(CONFIG_X2000_FB_LAYER_MIXER) += fb_layer_mixer.c
src-$(CONFIG_X2000_DPU_HAL) += dpu_hal.c
src-$(CONFIG_X2000_ROTATOR) += rotator.c

src-$(CONFIG_SFC_NOR) += sfc_common.c sfc_nor.c
src-$(CONFIG_SFC_NAND) += sfc_common.c sfc_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/ato_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/cochipgo_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/gd_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/esmt_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/mxic_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/nand_common.c
src-$(CONFIG_SFC_NAND) += nand_device/winbond_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/xtx_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/foresee_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/zetta_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/dosilicon_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/fm_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/issi_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/issi_mid9d_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/tc_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/xcsp_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/xtx_mid0b_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/xtx_mid2c_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/yhy_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/etron_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/gsto_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/hik_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/kowin_mid01_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/kowin_midc9_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/kowin_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/micron_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/unim_nand.c
src-$(CONFIG_SFC_NAND) += nand_device/wodposit_nand.c

src-$(CONFIG_X2000_ICODEC) += icodec.c
src-$(CONFIG_X2000_AUDIO) += audio_dma.c
src-$(CONFIG_X2000_AIC) += aic.c aic_playback.c aic_capture.c
src-$(CONFIG_X2000_DMIC) += dmic.c dmic_capture.c

src-$(CONFIG_X2000_CONN) += conn/conn.c
src-$(CONFIG_X2000_CONN_VIC) += conn_vic/conn_vic.c
src-$(CONFIG_X2000_CONN_FB) += conn_fb/conn_fb.c
src-$(CONFIG_X2000_CONN_ISP) += conn_isp/conn_isp.c
src-$(CONFIG_X2000_CONN_BLK) += conn_blk/conn_blk.c
src-$(CONFIG_X2000_CONN_PCM_PLAYBACK) += conn_pcm/conn_pcm_playback.c
src-$(CONFIG_X2000_CONN_FS) += conn_fs/conn_fs.c

src-$(CONFIG_X2000_PM) += pm/pm_power.c
src-$(CONFIG_X2000_PM) += pm/pm_sleep.c
src-$(CONFIG_X2000_PM) += pm/regs_save_restore.S

src-$(CONFIG_X2000_VPU_JPEG_ENCODE) += jpeg_encoder/jpeg_encode2.c

src-$(CONFIG_X2000_SCBOOT_DRIVER) += scboot/scboot.c
