
CFLAGS += -Ios/freertos/include

# src-y += heap_4.c
src-y += heap_extern_malloc.c
src-y += list.c
src-y += queue.c
src-y += tasks.c

src-y += port_xburst.c
src-y += wait_queue.c
src-y += os.c
src-y += thread.c
src-y += thread_cond_and_mutex.c
src-y += critical_thread_cond.c
src-y += thread_waiter.c
src-y += cmsis_os.c
src-y += semaphore.c