src-$(CONFIG_X1000_SLCD_TRULY240240) += lcd/x1000/lcd_truly240240.c
src-$(CONFIG_X1000_SLCD_ST7789V) += lcd/x1000/lcd_st7789v.c

src-$(CONFIG_X1830_TFT_ST7701) += lcd/x1830/lcd_st7701.c
src-$(CONFIG_X1830_SLCD_KWH035) += lcd/x1830/lcd_kwh035.c
src-$(CONFIG_X1830_SLCD_ST7789) += lcd/x1830/lcd_st7789.c

src-$(CONFIG_X1021_SLCD_KWH035) += lcd/x1021/lcd_kwh035.c

src-$(CONFIG_X2000_MIPI_KD070D57) += lcd/x2000/lcd_kd070d57.c
src-$(CONFIG_X2000_MIPI_FW050) += lcd/x2000/lcd_fw050.c
src-$(CONFIG_X2000_SLCD_KWH035) += lcd/x2000/lcd_kwh035.c
src-$(CONFIG_X2000_SLCD_JD9851) += lcd/x2000/lcd_jd9851.c
src-$(CONFIG_X2000_MIPI_OTM8018B) += lcd/x2000/lcd_otm8018b.c
src-$(CONFIG_X2000_TFT_ST7701) += lcd/x2000/lcd_st7701.c
src-$(CONFIG_X2000_TFT_ST7789V2) += lcd/x2000/lcd_st7789v2.c

src-$(CONFIG_X1600_SLCD_KWH035) += lcd/x1600/lcd_kwh035.c
src-$(CONFIG_X1600_TFT_ST7701) += lcd/x1600/lcd_st7701.c
src-$(CONFIG_X1600_SLCD_ST7789V_4LINE_SPI) += lcd/x1600/lcd_st7789v_4line_spi.c
src-$(CONFIG_X1600_TFT_ST77903_8BIT) += lcd/x1600/lcd_st77903_8bit.c

src-$(CONFIG_X2600_MIPI_FW050) += lcd/x2600/lcd_fw050.c
src-$(CONFIG_X2600_MIPI_YC101) += lcd/x2600/lcd_yc101.c
src-$(CONFIG_X2600_LVDS_KX070) += lcd/x2600/lcd_kx070.c
src-$(CONFIG_X2600_LVDS_QM101) += lcd/x2600/lcd_qm101.c
src-$(CONFIG_X2600_LVDS_X810) += lcd/x2600/lcd_x810.c

src-$(CONFIG_X2600_SLCD_ST7789V_4LINE_SPI) += lcd/x2600/lcd_st7789v_4line_spi.c
src-$(CONFIG_X2600_SLCD_ST7789V_3LINE_SPI) += lcd/x2600/lcd_st7789v_3line_spi.c
src-$(CONFIG_X2600_MIPI_ILI9881C_FW101) += lcd/x2600/lcd_ili9881c_fw101.c
src-$(CONFIG_X2600_MIPI_GM8775C) += lcd/x2600/lcd_gm8775c_data.c
src-$(CONFIG_X2600_TFT_SAT101) += lcd/x2600/lcd_sat101.c
src-$(CONFIG_X2600_TFT_NV3047_EP4303) += lcd/x2600/lcd_nv3047_ep4303.c
src-$(CONFIG_X2600_TFT_NV3031A) += lcd/x2600/lcd_nv3031a.c

src-$(CONFIG_AD100_MIPI_B203A) += lcd/ad100/lcd_b203a.c
src-$(CONFIG_AD100_MIPI_FW050) += lcd/ad100/lcd_fw050.c
src-$(CONFIG_AD100_MIPI_ILI9881C_FW101) += lcd/ad100/lcd_ili9881c_fw101.c
src-$(CONFIG_AD100_MIPI_HJ050) += lcd/ad100/lcd_hj050.c
src-$(CONFIG_AD100_MIPI_YC101) += lcd/ad100/lcd_yc101.c
src-$(CONFIG_AD100_TFT_ILI6122_JH050) += lcd/ad100/lcd_ili6122_jh050.c
src-$(CONFIG_AD100_MIPI_JD9165) += lcd/ad100/lcd_jd9165.c
src-$(CONFIG_AD100_MIPI_JD9365_M101) += lcd/ad100/lcd_jd9365_m101.c
src-$(CONFIG_AD100_MIPI_JD9365_L050) += lcd/ad100/lcd_jd9365_l050.c
src-$(CONFIG_AD100_MIPI_LD047RF1L01) += lcd/ad100/lcd_ld047rf1l01.c
src-$(CONFIG_AD100_MIPI_QM047KS01) += lcd/ad100/lcd_qm047ks01.c
src-$(CONFIG_AD100_MIPI_QM047KS02) += lcd/ad100/lcd_qm047ks02.c
src-$(CONFIG_AD100_MIPI_ST7283) += lcd/ad100/lcd_st7283.c
src-$(CONFIG_AD100_TFT_NV3074E_8BIT) += lcd/ad100/lcd_nv3074e.c
src-$(CONFIG_AD100_MIPI_GC9503V_TB045) += lcd/ad100/lcd_gc9503v_tb045.c
src-$(CONFIG_AD100_MIPI_ST7701S_TB039) += lcd/ad100/lcd_st7701s_tb039.c
src-$(CONFIG_AD100_MIPI_ST7701S) += lcd/ad100/lcd_st7701s.c
src-$(CONFIG_AD100_MIPI_ST7701S_FRD450) += lcd/ad100/lcd_st7701s_frd450.c
src-$(CONFIG_AD100_MIPI_ST7701S_ZX) += lcd/ad100/lcd_st7701s_zx.c
src-$(CONFIG_AD100_MIPI_ST7701S_TL021) += lcd/ad100/lcd_st7701s_tl021.c
src-$(CONFIG_AD100_MIPI_FL7703_TL040) += lcd/ad100/lcd_fl7703_tl040.c
src-$(CONFIG_AD100_MIPI_FL7703N)+= lcd/ad100/lcd_fl7703n.c
src-$(CONFIG_AD100_MIPI_ST7701S_SY) += lcd/ad100/lcd_st7701s_sy.c
src-$(CONFIG_AD100_MIPI_ST7797) += lcd/ad100/lcd_st7797.c
src-$(CONFIG_AD100_MIPI_ST7701S_TL028) += lcd/ad100/lcd_st7701s_tl028.c
src-$(CONFIG_AD100_TFT_ST7701S_50H9005) += lcd/ad100/lcd_st7701s_50H9005_9bit_spi.c
src-$(CONFIG_AD100_SLCD_ST7789V_3LINE_SPI) += lcd/ad100/lcd_st7789v_3line_spi.c
src-$(CONFIG_AD100_MIPI_ST7701_B041) += lcd/ad100/lcd_st7701_b041.c
src-$(CONFIG_AD100_MIPI_GC9503_HL062) += lcd/ad100/lcd_gc9503_hl062.c
src-$(CONFIG_AD100_MIPI_TP0P219) += lcd/ad100/lcd_tp0p219.c
src-$(CONFIG_AD100_MIPI_BH065) += lcd/ad100/lcd_bh065.c
src-$(CONFIG_AD100_LCD_ST7701S_BOE3) += lcd/ad100/lcd_st7701s_boe3.c
src-$(CONFIG_AD100_MIPI_HL06671028) += lcd/ad100/lcd_hl06671028.c
src-$(CONFIG_AD100_MIPI_ST7701S_NDB39) += lcd/ad100/lcd_st7701s_ndb39.c
src-$(CONFIG_AD100_SLCD_ILI9844_T502) += lcd/ad100/lcd_ili9844_t502.c
src-$(CONFIG_AD100_MIPI_JD9365) += lcd/ad100/lcd_jd9365.c
src-$(CONFIG_AD100_SLCD_JD9853) += lcd/ad100/lcd_jd9853.c
src-$(CONFIG_AD100_MIPI_GC9503CV) += lcd/ad100/lcd_gc9503cv.c
src-$(CONFIG_AD100_MIPI_RS070WS161) += lcd/ad100/lcd_rs070ws161.c
src-$(CONFIG_AD100_MIPI_RM692E5) += lcd/ad100/lcd_rm692e5.c
src-$(CONFIG_AD100_TFT_GC9503CV_FW50) += lcd/ad100/lcd_gc9503cv_fw50.c
src-$(CONFIG_AD100_MIPI_BM4021) += devices/lcd/ad100/lcd_bm4021.c
src-$(CONFIG_AD100_SLCD_GC9307) += lcd/ad100/lcd_gc9307.c
src-$(CONFIG_AD100_SLCD_GC9307_28CC) += lcd/ad100/lcd_gc9307_28cc.c
src-$(CONFIG_AD100_LVDS_ATT2089_NV156) += lcd/ad100/att2889_nv156/lcd_nv156.c
src-$(CONFIG_AD100_MIPI_ILI9881D) += lcd/ad100/lcd_ili9881d.c
src-$(CONFIG_AD100_MIPI_ST7703) += lcd/ad100/lcd_st7703.c
src-$(CONFIG_AD100_MIPI_NV3866A) += lcd/ad100/lcd_nv3866a.c
src-$(CONFIG_AD100_MIPI_RS101WX031) += lcd/ad100/lcd_rs101wx031.c
src-$(CONFIG_AD100_SLCD_ST7789P3) += lcd/ad100/lcd_st7789p3.c

src-$(CONFIG_LCD_ILCDTOOLS) += lcd/ilcdtools/ilt_utils.c
src-$(CONFIG_LCD_ILCDTOOLS) += lcd/ilcdtools/ilt_transfer_gpio.c
src-$(CONFIG_LCD_ILCDTOOLS) += lcd/ilcdtools/ilt_data.c
ifdef CONFIG_LCD_ILCDTOOLS
src-$(CONFIG_SOC_AD100) += lcd/ilcdtools/platform/ad100_config.c
src-$(CONFIG_SOC_X2600) += lcd/ilcdtools/platform/x2600_config.c
endif
